Fixed incorrect changed path when mutating unrelated area of proxy during iteration operations on cloned areas of the proxy.
sindresorhus/on-change pull request #105
Opened 2024-01-11 11:22 UTC by brendon1982

Hi,

I've been using your fantastic library in a side project, and I picked up an edge case that occurs when iterating over some part of the proxy and during that iteration modify a different part of the proxy. In this case the change path reported as the property currently being iterated over instead of the mutated property.

For example, if I have this object:
```
{
  a: [
    {
    quantity: 1
    }
  ],
  b: {
    c: {
      quantity: 8,
    },
  }
};
```

And I do the following:

```
proxy.a.forEach(() => {
  proxy.b.c = {
    quantity: 3,
  };
});
```

The expected change path is ```b.c```, however, it is reported as ```a```.

The issue seems to be that the ```handleChange``` would detect that a ```SmartClone``` is active, due to the ```forEach```, and therefore branch into the logic for updating the clone without first checking if the change path applies to the clone.

2024-01-11 13:27 UTC, brendon1982 commented
Hi,

It seems like I failed pretty hard on the eslint side and have had to make additional commits to address the issues.

Would you prefer that I make a new pull request with everything squashed?

2024-01-13 11:45 UTC, sindresorhus commented
> Would you prefer that I make a new pull request with everything squashed?

No. I will squash on merge.

2024-01-13 11:49 UTC, sindresorhus requested changes

2024-01-13 11:49 UTC, sindresorhus commented on lib/path.js
> +		if (path.indexOf(subPath) === 0) {
Use `String#startsWith`

2024-01-13 17:25 UTC, brendon1982 commented on lib/path.js
> +		if (path.indexOf(subPath) === 0) {
Thanks for the review, done :D

2024-01-14 06:09 UTC, merged